#! /bin/zsh

# Autostart programs
sxhkd &
compton &
$HOME/usr/dev/nixUtil/startLemonBar.sh 1880
~/.fehbg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          	1
bspc config window_gap           	20
bspc config click_to_focus	 	false
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus       false

bspc config split_ratio          	0.5 # 0.52 Default
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

bspc rule -a Firefox desktop='^3' follow=on
bspc rule -a Thunar desktop='^4' follow=on state=floating
bspc rule -a Sublime_text desktop='^2' follow=on
bspc rule -a QtCreator desktop='^4' follow=on
bspc rule -a KeePass2 desktop='^9' follow=on state=floating

