#! /bin/sh

# Source wal colors
. "${HOME}/.cache/wal/colors.sh"

# Start programs
sxhkd &
compton &
${HOME}/usr/dev/nixUtil/startLemonBar.sh 1880

bspc monitor -d I II III IV V VI VII VIII IX X

# Color Setup (via Wal)
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# Arbitrary Config Settings
bspc config border_width          	1
bspc config window_gap           	20
bspc config click_to_focus	 	false
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus       false

bspc config split_ratio          	0.5 # 0.52 Default
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

# Application Rules
bspc rule -a Firefox desktop='^3' follow=on
bspc rule -a Thunar desktop='^4' follow=on state=floating
bspc rule -a Sublime_text desktop='^2' follow=on
bspc rule -a QtCreator desktop='^4' follow=on
bspc rule -a KeePass2 desktop='^9' follow=on state=floating

